name: julia nightly
on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "1 0 1,15 * *"

jobs:
  testMKLjl:
    name: ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - "nightly"
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - name: Cache artifacts
        uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest

  # testAptMKL:
  #   name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       version:
  #         - 'nightly'
  #       os:
  #         - ubuntu-latest
  #       arch:
  #         - x64
  #   env:
  #       LD_LIBRARY_PATH: /opt/intel/compilers_and_libraries_2019.4.243/linux/mkl/lib/intel64_lin/
  #   steps:
  #     - name: Install MKL via apt
  #       run: |
  #         curl https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB > GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
  #         sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
  #         rm GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
  #         sudo sh -c 'echo deb https://apt.repos.intel.com/mkl all main > /etc/apt/sources.list.d/intel-mkl.list'
  #         sudo apt-get update
  #         sudo apt-get install -y intel-mkl-64bit-2019.4-070
  #         source /opt/intel/mkl/bin/mklvars.sh intel64
  #     - uses: actions/checkout@v2
  #     - uses: julia-actions/setup-julia@latest
  #       with:
  #         version: ${{ matrix.version }}
  #         arch: ${{ matrix.arch }}
  #     - uses: julia-actions/julia-buildpkg@latest
  #     - uses: julia-actions/julia-runtest@latest
